[package]
name = "revent"
version = "0.5.0"
license = "LGPL-3.0"
description = "Event system for Rust"
authors = ["Kevin Robert Stravers <macocio@gmail.com>"]
edition = "2018"
documentation = "https://docs.rs/revent"
repository = "https://github.com/BourgondAries/revent.git"
homepage = "https://github.com/BourgondAries/revent.git"

[dependencies]
crossbeam = "0.7.3"
crossbeam-channel = "0.4"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "storage"
harness = false
